version: "3"

sercvices:
  web:
    build: ./monitoring_docker
    volumes:
      - shared-data:/code/production
    ports:
      - "5000:80"
    depends-on:
      - store
    environment:
      - ENABLE_METRICS=true

  store:
    build: ./feature_store_docker
    volumes:
      - shared-data:/code/datas
    ports:
      - "21571:21571"

volumes:
  shared-data:
