version: "3"

services:
  web:
    build: ./monitoring_docker
    volumes:
      - shared-data:/code/datas
    ports:
      - "5000:80"
    depends_on:
      store:
        condition: service_completed_successfully
    environment:
      - ENABLE_METRICS=true
    command: bash -c "cd /manager && uvicorn app.api:app --host 0.0.0.0 --port 80"

  store:
    build: ./feature_store_docker
    volumes:
      - shared-data:/code/datas
    ports:
      - "21571:21571"

    command: bash -c "python get_data.py && feast apply"

volumes:
  shared-data:
