version: "3"

services:
  web:
    build: ./monitoring_docker
    volumes:
      - shared-data:/code/datas
    ports:
      - "5000:80"
    depends_on:
      - store
    environment:
      - ENABLE_METRICS=true
    restart: always
    command: python train.py

  store:
    build: ./feature_store_docker
    volumes:
      - shared-data:/code/datas
    ports:
      - "21571:21571"

    command: bash -c "python get_data.py && feast apply"

volumes:
  shared-data:
