version: "3"

services:
  web:
    build: 
      context: .
      dockerfile: ./monitoring_docker
    volumes:
      - shared-data:/code/production
    ports:
      - "5000:80"
    depends-on:
      - store
    environment:
      - ENABLE_METRICS=true
    restart: always
    command: tail -f /dev/null

  store:
    build: 
      context: .
      dockerfile: ./feature_store_docker
    volumes:
      - shared-data:/code/datas
    ports:
      - "21571:21571"

volumes:
  shared-data:
